# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_philipp.ipynb.

# %% auto 0
__all__ = ['psfoo', 'say_hello']

# %% ../00_philipp.ipynb 3
def psfoo(x): return x*x 

# %% ../00_philipp.ipynb 5
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
